### ISSUE TITLE
help it no work andrid

### ISSUE THREAD

**Issue by Sakooooo** [112cxyz/checkpa1n#4]
men why no work on anoroid i buy from china it keep saying "你妈妈是个大胖子" i dont know what it meant but i got banned from tiktok shortly after for saying bad things for an unrelated reason to this issue polease fix need android 
please add chatggpt support for linux

ChatGPT: Optimizing
Language Models
for Dialogue

We’ve trained a model called ChatGPT which interacts in a conversational way. The dialogue format makes it possible for ChatGPT to answer followup questions, admit its mistakes, challenge incorrect premises, and reject inappropriate requests. ChatGPT is a sibling model to [InstructGPT](https://openai.com/blog/instruction-following/), which is trained to follow an instruction in a prompt and provide a detailed response.
[Try ChatGPT](https://chat.openai.com/)
November 30, 2022
13 minute read
ChatGPT: Optimizing Language Models for Dialogue

We are excited to introduce ChatGPT to get users’ feedback and learn about its strengths and weaknesses. During the research preview, usage of ChatGPT is free. Try it now at [chat.openai.com](https://chat.openai.com/). qwhat help please they are here

**Comment by 112cxyz** [comment]
i men it shod work on andreid you just gottah recompiles it from the sausecode with a .apk with chatgpt compiler.

men

112c@112c.co.uk (: 👍🏻

**Comment by Sakooooo** [comment]
gksifpgomrqwp;a fkl;amvruji0asegbuy انت بنت لانك ولاد من امركه the palace...................
